<?xml version="1.0" encoding="utf-8"?><Database Name="DbQuanLyResort" Class="QLResortDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ADMIN-PC\SQLEXPRESS;Initial Catalog=DbQuanLyResort;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="DbQuanLyResortConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ComboMonAn" Member="ComboMonAns">
    <Type Name="ComboMonAn">
      <Column Name="maCB" Type="System.String" DbType="VarChar(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenCB" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="giaCB" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="ComboMonAn_ChiTiecDatTiec" Member="ChiTiecDatTiecs" ThisKey="maCB" OtherKey="maCB" Type="ChiTiecDatTiec" />
      <Association Name="ComboMonAn_ChiTietCombo" Member="ChiTietCombos" ThisKey="maCB" OtherKey="maCB" Type="ChiTietCombo" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="taikhoan" Member="taikhoan1" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Association Name="NhanSu_TaiKhoan" Member="NhanSu" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="NhanSu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTiecDatTiec" Member="ChiTiecDatTiecs">
    <Type Name="ChiTiecDatTiec">
      <Column Name="maCTDT" Type="System.String" DbType="VarChar(14) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="maCB" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="maMA" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ComboMonAn_ChiTiecDatTiec" Member="ComboMonAn" ThisKey="maCB" OtherKey="maCB" Type="ComboMonAn" IsForeignKey="true" />
      <Association Name="DatTiec_ChiTiecDatTiec" Member="DatTiec" ThisKey="maDT" OtherKey="maDT" Type="DatTiec" IsForeignKey="true" />
      <Association Name="MonAn_ChiTiecDatTiec" Member="MonAn" ThisKey="maMA" OtherKey="maMA" Type="MonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietCombo" Member="ChiTietCombos">
    <Type Name="ChiTietCombo">
      <Column Name="maCTCB" Type="System.String" DbType="VarChar(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maCB" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="maMA" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Association Name="ComboMonAn_ChiTietCombo" Member="ComboMonAn" ThisKey="maCB" OtherKey="maCB" Type="ComboMonAn" IsForeignKey="true" />
      <Association Name="MonAn_ChiTietCombo" Member="MonAn" ThisKey="maMA" OtherKey="maMA" Type="MonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDatDichVu" Member="ChiTietDatDichVus">
    <Type Name="ChiTietDatDichVu">
      <Column Name="maCTDDV" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="maDV" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="DatTiec_ChiTietDatDichVu" Member="DatTiec" ThisKey="maDT" OtherKey="maDT" Type="DatTiec" IsForeignKey="true" />
      <Association Name="DichVu_ChiTietDatDichVu" Member="DichVu" ThisKey="maDV" OtherKey="maDV" Type="DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietDatPhong" Member="ChiTietDatPhongs">
    <Type Name="ChiTietDatPhong">
      <Column Name="maDP" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ngayTraPhong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="ChiTietDatPhong_HoaDonDatPhong" Member="HoaDonDatPhongs" ThisKey="maCTDP" OtherKey="maCTDP" Type="HoaDonDatPhong" />
      <Association Name="ChiTietDatPhong_SuDungDichVu" Member="SuDungDichVus" ThisKey="maCTDP" OtherKey="maCTDP" Type="SuDungDichVu" />
      <Association Name="DatPhong_ChiTietDatPhong" Member="DatPhong" ThisKey="maDP" OtherKey="maDP" Type="DatPhong" IsForeignKey="true" />
      <Association Name="LoaiHinhLuuTru_ChiTietDatPhong" Member="LoaiHinhLuuTru" ThisKey="maLH" OtherKey="maLH" Type="LoaiHinhLuuTru" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaChucVu" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ChucVu_NhanSu" Member="NhanSus" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="NhanSu" />
    </Type>
  </Table>
  <Table Name="dbo.DatPhong" Member="DatPhongs">
    <Type Name="DatPhong">
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="maDP" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngayDatPhong" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="DatPhong_ChiTietDatPhong" Member="ChiTietDatPhongs" ThisKey="maDP" OtherKey="maDP" Type="ChiTietDatPhong" />
      <Association Name="KhachHang_DatPhong" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanSu_DatPhong" Member="NhanSu" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="NhanSu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DatTiec" Member="DatTiecs">
    <Type Name="DatTiec">
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="maDT" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngayDT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="maS" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="giaTriDC" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="DatTiec_ChiTiecDatTiec" Member="ChiTiecDatTiecs" ThisKey="maDT" OtherKey="maDT" Type="ChiTiecDatTiec" />
      <Association Name="DatTiec_ChiTietDatDichVu" Member="ChiTietDatDichVus" ThisKey="maDT" OtherKey="maDT" Type="ChiTietDatDichVu" />
      <Association Name="DatTiec_HoaDonDatTiec" Member="HoaDonDatTiecs" ThisKey="maDT" OtherKey="maDT" Type="HoaDonDatTiec" />
      <Association Name="KhachHang_DatTiec" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanSu_DatTiec" Member="NhanSu" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="NhanSu" IsForeignKey="true" />
      <Association Name="SanhDatTiec_DatTiec" Member="SanhDatTiec" ThisKey="maS" OtherKey="maS" Type="SanhDatTiec" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="maDV" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenDV" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="giaTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DichVu_ChiTietDatDichVu" Member="ChiTietDatDichVus" ThisKey="maDV" OtherKey="maDV" Type="ChiTietDatDichVu" />
      <Association Name="DichVu_SuDungDichVu" Member="SuDungDichVus" ThisKey="maDV" OtherKey="maDV" Type="SuDungDichVu" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonDatPhong" Member="HoaDonDatPhongs">
    <Type Name="HoaDonDatPhong">
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="maHDDP" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="maSDDV" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="ChiTietDatPhong_HoaDonDatPhong" Member="ChiTietDatPhong" ThisKey="maCTDP" OtherKey="maCTDP" Type="ChiTietDatPhong" IsForeignKey="true" />
      <Association Name="NhanSu_HoaDonDatPhong" Member="NhanSu" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="NhanSu" IsForeignKey="true" />
      <Association Name="SuDungDichVu_HoaDonDatPhong" Member="SuDungDichVu" ThisKey="maSDDV" OtherKey="maSDDV" Type="SuDungDichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonDatTiec" Member="HoaDonDatTiecs">
    <Type Name="HoaDonDatTiec">
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="maHDDT" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="DatTiec_HoaDonDatTiec" Member="DatTiec" ThisKey="maDT" OtherKey="maDT" Type="DatTiec" IsForeignKey="true" />
      <Association Name="NhanSu_HoaDonDatTiec" Member="NhanSu" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="NhanSu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoDT" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_DatPhong" Member="DatPhongs" ThisKey="MaKH" OtherKey="MaKH" Type="DatPhong" />
      <Association Name="KhachHang_DatTiec" Member="DatTiecs" ThisKey="MaKH" OtherKey="MaKH" Type="DatTiec" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiHinhLuuTru" Member="LoaiHinhLuuTrus">
    <Type Name="LoaiHinhLuuTru">
      <Column Name="maLH" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenLH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="loaiHinh" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="slNguoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="giaTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
      <Association Name="LoaiHinhLuuTru_ChiTietDatPhong" Member="ChiTietDatPhongs" ThisKey="maLH" OtherKey="maLH" Type="ChiTietDatPhong" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiMonAn" Member="LoaiMonAns">
    <Type Name="LoaiMonAn">
      <Column Name="maLMA" Type="System.String" DbType="VarChar(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenLMA" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiMonAn_MonAn" Member="MonAns" ThisKey="maLMA" OtherKey="maLMA" Type="MonAn" />
    </Type>
  </Table>
  <Table Name="dbo.MonAn" Member="MonAns">
    <Type Name="MonAn">
      <Column Name="maMA" Type="System.String" DbType="VarChar(7) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maLMA" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="tenMA" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="giaTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="mieuTa" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="MonAn_ChiTiecDatTiec" Member="ChiTiecDatTiecs" ThisKey="maMA" OtherKey="maMA" Type="ChiTiecDatTiec" />
      <Association Name="MonAn_ChiTietCombo" Member="ChiTietCombos" ThisKey="maMA" OtherKey="maMA" Type="ChiTietCombo" />
      <Association Name="LoaiMonAn_MonAn" Member="LoaiMonAn" ThisKey="maLMA" OtherKey="maLMA" Type="LoaiMonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanSu" Member="NhanSus">
    <Type Name="NhanSu">
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="CCCD" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MaChucVu" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="NhanSu_TaiKhoan" Member="TaiKhoans" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="TaiKhoan" />
      <Association Name="NhanSu_DatPhong" Member="DatPhongs" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="DatPhong" />
      <Association Name="NhanSu_DatTiec" Member="DatTiecs" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="DatTiec" />
      <Association Name="NhanSu_HoaDonDatPhong" Member="HoaDonDatPhongs" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="HoaDonDatPhong" />
      <Association Name="NhanSu_HoaDonDatTiec" Member="HoaDonDatTiecs" ThisKey="MaNhanSu" OtherKey="MaNhanSu" Type="HoaDonDatTiec" />
      <Association Name="ChucVu_NhanSu" Member="ChucVu" ThisKey="MaChucVu" OtherKey="MaChucVu" Type="ChucVu" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.SanhDatTiec" Member="SanhDatTiecs">
    <Type Name="SanhDatTiec">
      <Column Name="maS" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenS" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="giaSDT" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="SanhDatTiec_DatTiec" Member="DatTiecs" ThisKey="maS" OtherKey="maS" Type="DatTiec" />
    </Type>
  </Table>
  <Table Name="dbo.SuDungDichVu" Member="SuDungDichVus">
    <Type Name="SuDungDichVu">
      <Column Name="maSDDV" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="maDV" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="SuDungDichVu_HoaDonDatPhong" Member="HoaDonDatPhongs" ThisKey="maSDDV" OtherKey="maSDDV" Type="HoaDonDatPhong" />
      <Association Name="ChiTietDatPhong_SuDungDichVu" Member="ChiTietDatPhong" ThisKey="maCTDP" OtherKey="maCTDP" Type="ChiTietDatPhong" IsForeignKey="true" />
      <Association Name="DichVu_SuDungDichVu" Member="DichVu" ThisKey="maDV" OtherKey="maDV" Type="DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.DSDatPhongTheoNam" Method="DSDatPhongTheoNam">
    <Parameter Name="SearchYear" Parameter="searchYear" Type="System.Int32" DbType="Int" />
    <ElementType Name="DSDatPhongTheoNamResult">
      <Column Name="maDP" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ngayDatPhong" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayTraPhong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="maLH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ThongKeDichVu_TheoThang" Method="sp_ThongKeDichVu_TheoThang">
    <Parameter Name="thang" Type="System.Int32" DbType="Int" />
    <Parameter Name="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ThongKeDichVu_TheoThangResult">
      <Column Name="tenDV" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="TongSoLanSuDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSDatPhongTheoNgay" Method="DSDatPhongTheoNgay">
    <Parameter Name="SearchDate" Parameter="searchDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="DSDatPhongTheoNgayResult">
      <Column Name="maDP" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ngayDatPhong" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayTraPhong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="maLH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSDatPhongTheoThang" Method="DSDatPhongTheoThang">
    <Parameter Name="Year" Parameter="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Month" Parameter="month" Type="System.Int32" DbType="Int" />
    <ElementType Name="DSDatPhongTheoThangResult">
      <Column Name="maDP" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ngayDatPhong" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayTraPhong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="maLH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSDatTiecTheoNam" Method="DSDatTiecTheoNam">
    <Parameter Name="SearchYear" Parameter="searchYear" Type="System.Int32" DbType="Int" />
    <ElementType Name="DSDatTiecTheoNamResult">
      <Column Name="maDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="maS" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ngayDT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="giaTriDC" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSDatTiecTheoNgay" Method="DSDatTiecTheoNgay">
    <Parameter Name="SearchDate" Parameter="searchDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="DSDatTiecTheoNgayResult">
      <Column Name="maDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="maS" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ngayDT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="giaTriDC" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSDatTiecTheoThang" Method="DSDatTiecTheoThang">
    <Parameter Name="Year" Parameter="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Month" Parameter="month" Type="System.Int32" DbType="Int" />
    <ElementType Name="DSDatTiecTheoThangResult">
      <Column Name="maDT" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="maS" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="ngayDT" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="giaTriDC" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSHoaDonDatPhong" Method="DSHoaDonDatPhong">
    <ElementType Name="DSHoaDonDatPhongResult">
      <Column Name="maHDDP" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhanSu" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ngayLap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="maSDDV" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="soLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimChiTietDatPhongTheoTenLH" Method="sp_TimChiTietDatPhongTheoTenLH">
    <Parameter Name="tenLH" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="sp_TimChiTietDatPhongTheoTenLHResult">
      <Column Name="maCTDP" Type="System.String" DbType="VarChar(13) NOT NULL" CanBeNull="false" />
      <Column Name="maDP" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="maLH" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tenLH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="loaiHinh" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="ngayTraPhong" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemLoaiHinhLuuTru" Method="sp_TimKiemLoaiHinhLuuTru">
    <Parameter Name="tenLH" Type="System.String" DbType="NVarChar(5)" />
    <ElementType Name="sp_TimKiemLoaiHinhLuuTruResult">
      <Column Name="maLH" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="tenLH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="loaiHinh" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="slNguoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="giaTien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="trangThai" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="ghiChu" Type="System.String" DbType="NVarChar(120)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ThongKeDichVu_TheoNam" Method="sp_ThongKeDichVu_TheoNam">
    <Parameter Name="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ThongKeDichVu_TheoNamResult">
      <Column Name="tenDV" Type="System.String" DbType="NVarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="TongSoLanSuDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>